config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  
  namespace :api do
    namespace :v1 do
      get "/news", to: "news#news"
      get "/:fecha1/:fecha2", to: "news#limit"
      post "/tweet_from_api", to: "news#tweet_from_api"
        end
  end
  
  root 'home#index'
  
  resources :tweets do 
    member do
      post "retweet"
    end
  end
  resources :likes
  get "users", to: 'home#list_users', as:'list_users'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  post 'friends/:id', to: 'friends#create', as:'follow_friends'
  delete 'friends/:id', to: 'friends#destroy', as:'unfollow_friends'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :textweet, presence: true

  scope :tweets_for_me, -> (user) { where(user_id: user.friends.pluck(:friend_id)).or(where(user_id: user)) }


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy retweet ]
  
  # GET /tweets or /tweets.json

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet = Tweet.new(tweet_params.merge(user: current_user))
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

# buttton retweet
  def retweet
    redirect_to root_path, alert: "you can't retweet yourself" and return if @tweet.user == current_user
    retweet_ready = Tweet.new(textweet: @tweet.textweet)
    retweet_ready.user = current_user
    retweet_ready.ref_id_tweet = @tweet.id
    if retweet_ready.save
      if @tweet.retweet.nil?
          @tweet.update(retweet: @tweet.retweet = 1)  
      else
        
        @tweet.update(retweet: @tweet.retweet += 1)
      end
      
      redirect_to root_path, notice: 'retweet successfully entered'
    end 
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:textweet, :retweet, :tweet_photo, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <div class="field">
    <h3>Nuevo Tweet</h3>
    <%= form.text_area  :textweet %>
  </div>

  <div class="actions">
    <%= form.submit"Twittear", :class => 'btn text-light' %>
  </div>
</div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', root_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', root_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="border border-secondary container bg-light my-45">
      <p class="h3">
        <strong>Textweet:</strong>
        <%= @tweet.textweet %>
      </p>
      <p>
        <strong>Retweet:</strong>
        <%= @tweet.retweet %>
      </p>
      <p>
        <strong>User:</strong>
        <%= @tweet.user.nickname %>
        <img src="<%= @tweet.user.profile_photo %>" height="45" width="45" class="border border-black rounded-circle" alt="">
      </p>

      <p>
        <strong>Usuarios que dieron likes:</strong>
        <% @tweet.likes.each do |like|%>
        <img src="<%= like.user.profile_photo %>" weight="40px" height="40px" class=" border border-black rounded-circle" alt="">
        <% end %>
      </p>
      <% if @tweet.user_id == current_user.id%>
        <%= link_to edit_tweet_path(@tweet) do %> 
        <i class="fas fa-edit fa-2x"></i>
          <% end %>
        <%= link_to root_path do %> |
        <i class="fas fa-arrow-circle-left fa-2x"></i>
          <% end %> |
        <%= link_to @tweet, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fas fa-trash-alt fa-2x"></i>
          <% end %>
      <% end  %>
</div>