config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  
  namespace :api do
    namespace :v1 do
      get "/news", to: "news#news"
      get "/:fecha1/:fecha2", to: "news#limit"
      post "/tweet_from_api", to: "news#tweet_from_api"
        end
  end
  
  root 'home#index'
  
  resources :tweets do 
    member do
      post "retweet"
    end
  end
  resources :likes
  get "users", to: 'home#list_users', as:'list_users'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  post 'friends/:id', to: 'friends#create', as:'follow_friends'
  delete 'friends/:id', to: 'friends#destroy', as:'unfollow_friends'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!
  def index
    
    if signed_in?
      @tweets = Tweet.tweets_for_me(current_user).order("created_at DESC")
      if params[:q].present?
        @tweets = Tweet.tweets_for_me(current_user).order("created_at DESC").where('textweet LIKE ?', "%#{params[:q]}%")
      end
    else
      @tweets = Tweet.all.order("created_at DESC")
      if params[:q].present?
        @tweets = Tweet.where('textweet LIKE ?', "%#{params[:q]}%")
      end
    end
    

    @tweets = Kaminari.paginate_array(@tweets).page(params[:page]).per(50)
    @tweet = Tweet.new
    @like = Like.new
    @friends = Friend.all
    @friend = Friend.new
  end

  def list_users
    @users = User.where.not(id: current_user.id)
    @friends = Friend.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <span class="h3"> <%= "Bienvenido @#{current_user.nickname}" %></span>

<% end %>
<p id="notice" ><%= notice %></p>

<% if user_signed_in?  %>
  <div class="border-bottom border-primary">
    <%= render 'tweets/form', tweet: @tweet %>
    </div>
  <% end %>
<br>
<h1 class="">Tweets</h1>

<div class = "container">
    <%= form_tag root_path, method: :get do %>
    <%= text_field_tag :q, nil, placeholder: 'Buscar Tweet', class:"my-2 my-sm-0"  %>
    <%= submit_tag "Buscar", class:"btn btn-outline-success my-2 my-sm-0" %>
    <%= link_to "Mostrar todos", root_path, class:'btn btn-outline-success my-2 my-sm-0 text-light'%>
<% end  %>

<br>

<% @tweets.each do |tweet| %>
  <div class="media border border-secondary mb-3 container bg-light">
  <div class="mr-4 text-center"> 
    <img src="<%= tweet.user.profile_photo %>" height="64" width="64" class="m-2 border border-black rounded-circle" alt="">
      <% if user_signed_in?  %> 
      <p>
        <% if tweet.user_id != current_user.id  %>
              <% pre_follow = @friends.find{|friend| friend.user_id == current_user.id && friend.friend_id == tweet.user_id} %>
              <% if pre_follow%>
              <%= link_to unfollow_friends_path(tweet.user_id), method: :delete,class:'btn btn-light btn-sm text-light' do %> Unfollow<% end %>
              <% else %>
              <%= link_to follow_friends_path(tweet.user_id), method: :post,class:'btn btn-light btn-sm text-light' do %> Follow<% end %>
              <% end %>
            <% end  %>
        <% end  %>
      </p>
    </div>
      <div class="media-body my-3">
        <span class="h5 mt-0 text-primary">@<%= tweet.user.nickname %></span> 
        <p class="h5 text-secondary"><% hashtag = tweet.textweet.split(" ") %></p>
        <% ed_words = [] %>
        <% hashtag.each do |word| %>
          <% if word.first == "#" %>
            <% word = link_to word%>
          <% end %>
          <% ed_words.push(word) %>
        <% end %>
        <p><%= raw ed_words.join(" ") %></p>
        <%= tweet.likes.count %><%= tweet.likes.count == 1? ' like': " Likes" %> | 
        <%= tweet.retweet %><%= tweet.retweet == 1? ' Retweet': " Retweets" %> |
        <%= link_to time_ago_in_words(tweet.created_at),tweet %> |
            <% if user_signed_in?  %>
                <% if tweet.ref_id_tweet != nil %>
                  <%= link_to "Ir a Tweet original", tweet_path(tweet.ref_id_tweet)%>
                <% end %>
            <% end %>
        <br>
        <div class="mt-2">
          <% if user_signed_in?  %>
              <% pre_like = tweet.likes.find {|like| like.user.id == current_user.id}  %> 
                <% if pre_like  %>
                    <%= link_to (like_path(tweet.id)), method: :delete do %>
                        <i class="fas fa-thumbs-up fa-2x text-primary"></i>
                      <% end %>  
                      <% else  %>
                        <%= link_to (likes_path(tweet.id)), method: :post do %>
                          <i class="far fa-thumbs-up fa-2x text-primary"></i>
                        <% end %> 
                      <% end %>
                      <%= link_to retweet_tweet_path(tweet), method: :post do %>
                        <i class="fas fa-retweet fa-2x text-primary"></i>
                          <% end %>
                        <%= link_to tweet_path(tweet) do %> 
                          <i class="fas fa-eye fa-2x text-primary"></i>
                            <% end %>
            <% end %>
          </div>
      </div>
  </div>
<% end %>

<div class="row ">
    <div class="col-md-8 offset-md-2">
        <%= link_to_prev_page @tweets, 'Volver',  class:' btn btn-link mx-2'%>
        <%= link_to_next_page @tweets, 'Mostrar mas tweet', class:'btn btn-link mx-2'%>
    </div>
</div>

app/views/home/list_users.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Foto Perfil</th>
      <th scope="col">nickname</th>
      <th scope="col">email</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td><img src="<%= user.profile_photo %>" height="64" width="64" class="m-2 border border-black rounded-circle" alt=""> </td>
        <td><%= user.nickname %></td>
        <td><%= user.email %></td>
        <td><%= link_to follow_friends_path(user.id), method: :post,class:'btn btn-light text-light' do %> Follow<% end %></td>
      </tr>
    <% end  %>
  </tbody>
</table>